# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: atlassian/default-image:2

build:
  stage: build
  script:
    - echo "Do your build here"
    - ls
    - cat ./run.sh | bash -s
