build:
  image: atlassian/default-image:2
  stage: build
  script:
    - echo "Do your build here"
    - ls
    - cat ./run.sh | bash -s
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always
